import type { Pin } from './types';

/**
 * Locally bundled fallback artwork.
 *
 * Original abstract vector posters generated by this project (no third-party
 * rights involved, so they are safe to ship and safe to show). They are used
 * in two situations only:
 *   • an <img> fails to load, so a card never renders as a broken tile;
 *   • the Openverse API is unreachable, so the feed is never blank.
 * They are abstract by construction, which also means they can never contain
 * explicit or horror imagery.
 */

interface ArtworkSpec {
  id: string;
  title: string;
  background: string;
  shapes: string;
  width: number;
  height: number;
}

const SPECS: ArtworkSpec[] = [
  {
    id: 'local-art-01', title: 'Hot pink graphic poster', background: '#FF3D8B', width: 600, height: 800,
    shapes: '<circle cx="300" cy="300" r="170" fill="#FFD84D"/><path d="M0 640h600v160H0z" fill="#C11162"/><circle cx="300" cy="300" r="92" fill="#FF3D8B"/>',
  },
  {
    id: 'local-art-02', title: 'Yellow character study', background: '#FFD23F', width: 600, height: 900,
    shapes: '<circle cx="300" cy="330" r="150" fill="#2B2B2B"/><path d="M150 900a150 150 0 0 1 300 0z" fill="#2B2B2B"/><circle cx="255" cy="310" r="22" fill="#FFD23F"/><circle cx="345" cy="310" r="22" fill="#FFD23F"/>',
  },
  {
    id: 'local-art-03', title: 'Orange and teal abstract', background: '#0F6E6B', width: 600, height: 780,
    shapes: '<path d="M0 0h600v300c-160 60-320-60-480 0S0 300 0 300z" fill="#F2742D"/><circle cx="420" cy="560" r="130" fill="#F2A65A"/>',
  },
  {
    id: 'local-art-04', title: 'Low key portrait backdrop', background: '#161616', width: 600, height: 820,
    shapes: '<ellipse cx="300" cy="360" rx="150" ry="190" fill="#3A3A3A"/><path d="M150 820a150 120 0 0 1 300 0z" fill="#4A4A4A"/><circle cx="300" cy="330" r="120" fill="#6B6B6B" opacity="0.35"/>',
  },
  {
    id: 'local-art-05', title: 'Vermilion editorial field', background: '#E8491F', width: 600, height: 810,
    shapes: '<circle cx="300" cy="340" r="160" fill="#F6C453"/><path d="M120 810a180 150 0 0 1 360 0z" fill="#8C1D18"/>',
  },
  {
    id: 'local-art-06', title: 'Red cinematic poster', background: '#C1121F', width: 560, height: 1180,
    shapes: '<path d="M0 0h560v260L0 420z" fill="#780000"/><circle cx="280" cy="640" r="150" fill="#FDF0D5"/><path d="M0 1180h560V980L0 1060z" fill="#780000"/>',
  },
  {
    id: 'local-art-07', title: 'Teal automotive abstract', background: '#114B5F', width: 600, height: 860,
    shapes: '<path d="M60 520h480l-60 120H120z" fill="#0A9396"/><circle cx="170" cy="660" r="46" fill="#E9D8A6"/><circle cx="430" cy="660" r="46" fill="#E9D8A6"/><path d="M0 260h600v40H0z" fill="#94D2BD" opacity="0.6"/>',
  },
  {
    id: 'local-art-08', title: 'Muted pink illustration', background: '#E7B7B1', width: 600, height: 750,
    shapes: '<circle cx="300" cy="300" r="140" fill="#6D4C41"/><path d="M170 750a130 110 0 0 1 260 0z" fill="#4E342E"/><circle cx="300" cy="300" r="96" fill="#E7B7B1"/>',
  },
  {
    id: 'local-art-09', title: 'Grey studio backdrop', background: '#8D8D8D', width: 600, height: 760,
    shapes: '<ellipse cx="300" cy="330" rx="140" ry="170" fill="#3E3E3E"/><path d="M160 760a140 120 0 0 1 280 0z" fill="#2F2F2F"/><circle cx="300" cy="300" r="70" fill="#C9C9C9" opacity="0.5"/>',
  },
  {
    id: 'local-art-10', title: 'Purple avatar study', background: '#7B2CBF', width: 600, height: 800,
    shapes: '<circle cx="300" cy="320" r="150" fill="#E0AAFF"/><path d="M150 800a150 130 0 0 1 300 0z" fill="#C77DFF"/><circle cx="300" cy="320" r="100" fill="#5A189A"/>',
  },
  {
    id: 'local-art-11', title: 'Monochrome editorial', background: '#212121', width: 600, height: 900,
    shapes: '<circle cx="300" cy="340" r="155" fill="#EDEDED"/><path d="M140 900a160 140 0 0 1 320 0z" fill="#EDEDED"/><path d="M210 300h180v26H210z" fill="#212121"/>',
  },
  {
    id: 'local-art-12', title: 'Autumn outdoor study', background: '#A98467', width: 600, height: 810,
    shapes: '<circle cx="300" cy="330" r="145" fill="#6C584C"/><path d="M150 810a150 130 0 0 1 300 0z" fill="#6C584C"/><circle cx="470" cy="150" r="60" fill="#FFD8A8"/>',
  },
  {
    id: 'local-art-13', title: 'Deep teal portrait field', background: '#14532D', width: 600, height: 960,
    shapes: '<ellipse cx="300" cy="360" rx="150" ry="180" fill="#064E3B"/><path d="M150 960a150 140 0 0 1 300 0z" fill="#064E3B"/><circle cx="300" cy="330" r="100" fill="#D1FAE5" opacity="0.35"/>',
  },
  {
    id: 'local-art-14', title: 'Streetwear mirror composition', background: '#EDEDED', width: 560, height: 900,
    shapes: '<path d="M120 120h320v700H120z" fill="#D6D6D6"/><circle cx="280" cy="300" r="90" fill="#495057"/><path d="M190 900a90 130 0 0 1 180 0z" fill="#495057"/>',
  },
  {
    id: 'local-art-15', title: 'Mustard bird poster', background: '#E9C46A', width: 600, height: 1060,
    shapes: '<ellipse cx="300" cy="520" rx="150" ry="180" fill="#F4A261"/><circle cx="300" cy="330" r="95" fill="#F4A261"/><path d="M300 330l120-40-30 60z" fill="#E76F51"/><circle cx="270" cy="315" r="12" fill="#264653"/>',
  },
  {
    id: 'local-art-16', title: 'Burgundy tailoring study', background: '#6D1A36', width: 600, height: 830,
    shapes: '<path d="M300 220l120 90v520H180V310z" fill="#9D2235"/><circle cx="300" cy="200" r="95" fill="#E5B8A6"/><path d="M270 310h60v520h-60z" fill="#EDEDED" opacity="0.85"/>',
  },
  {
    id: 'local-art-17', title: 'Pattern tile', background: '#2A9D8F', width: 600, height: 720,
    shapes: '<g fill="#E9C46A"><circle cx="150" cy="180" r="60"/><circle cx="450" cy="180" r="60"/><circle cx="150" cy="540" r="60"/><circle cx="450" cy="540" r="60"/><circle cx="300" cy="360" r="80"/></g>',
  },
  {
    id: 'local-art-18', title: 'Blue wallpaper gradient', background: '#1D3557', width: 600, height: 880,
    shapes: '<path d="M0 0h600v880H0z" fill="#457B9D" opacity="0.35"/><circle cx="300" cy="440" r="180" fill="#A8DADC" opacity="0.55"/><circle cx="300" cy="440" r="100" fill="#F1FAEE" opacity="0.6"/>',
  },
];

const cache = new Map<string, string>();

function encode(svg: string): string {
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

/** Data URI for one piece of bundled artwork. */
export function artworkDataUri(index: number): string {
  const spec = SPECS[((index % SPECS.length) + SPECS.length) % SPECS.length];
  const hit = cache.get(spec.id);
  if (hit) return hit;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${spec.width} ${spec.height}" width="${spec.width}" height="${spec.height}">` +
    `<rect width="${spec.width}" height="${spec.height}" fill="${spec.background}"/>${spec.shapes}</svg>`;
  const uri = encode(svg);
  cache.set(spec.id, uri);
  return uri;
}

/**
 * Bundled artwork as pins, used when the API cannot be reached. Ratio variety
 * mirrors the reference (0.47–0.83) so the masonry stays staggered.
 */
export function fallbackPins(count = SPECS.length): Pin[] {
  return SPECS.slice(0, Math.max(1, Math.min(count, SPECS.length))).map((spec, index) => ({
    id: spec.id,
    title: spec.title,
    imageUrl: artworkDataUri(index),
    originalUrl: artworkDataUri(index),
    width: spec.width,
    height: spec.height,
    creator: 'Pinspire (bundled artwork)',
    license: 'cc0',
    licenseVersion: '1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution:
      `“${spec.title}” is original vector artwork bundled with this project and released under CC0 1.0.`,
    local: true,
    badge: index === 5 ? '3/9' : index === 14 ? '2/6' : undefined,
  }));
}

/** Neutral placeholder shown when a single image URL turns out to be broken. */
export function brokenImageReplacement(index: number): string {
  return artworkDataUri(index);
}
